
version: "3.3"
services:
  postgres:
    image: postgres:12
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    volumes:
      -  ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      -  ./sql_commands.sql:/docker-entrypoint-initdb.d/sql_commands.sql



