
version: "3.3"
services:
  postgres:
    image: postgres:12
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    volumes:
      -  ./src/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      -  ./src/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
      -  ./src/sql_query.sql:/docker-entrypoint-initdb.d/sql_query.sql




